var aCoalFldADRA=["ADRA- ADRA",
"BHARAT COOKING COAL LTD ADRA- BCCL","CENTRAL COAL FIELDS ADRA- CCL","STEEL AUTHORITY OF INDIA LTD- SAIL","TATA STEEL LTD ADRA- TICS","TATA STEEL LTD ADRA- TISC"];

var aCoalFldASN=["ASANSOAL COAL FIELDS- ASN",
"M/S STEEL AUTHORITY OF INDIA LTD- SAIL"];

var aCoalFldBSP=["ACB (INDIA) LIMITED- ACB",
"M/S BHARAT ALLUMINIUM COMPANY LTD- BALC","BHATIA ENERGY AND MINERALS PVT LTD- BEMP","M/S CLEAN COAL ENTERPRISES PVT LTD- CCEP","GLOBAL COAL AND MINING PVT LTD- GCML","HIND ENERGY AND COAL BENEFICATION(INDIA) LTD- HECB","IB VALLEY- IB","INDU- INDU","M/S JINDAL POWER LTD- JDPL","M/S JINDAL STEEL AND POWER LTD- JSPL","KOREA REWA- KR","KORBA- KRBR","MAHESWARI COAL BENEFICT AND INFRA PVT LTD- MCBI","M/S MAHANADI COALFIELD LTD.- MCFL","M/S MAHAVIR COAL WASHERIES PRIVATE LIMITED- MCWP","M/S MAHAVIR BENEFICATION PRIVATE LIMITED- MHBN","PHIL COAL BENEFICATION PVT LTD- PCPB","M/S PHIL MINERALS BENEFICATION AND ENERGY PVT- PMBE","RAIGARH- RIG","RRVU- RRVU","RAJASTHAN VIDYUT UTPADAN NIGAM LTD. (RVUNL)- RVUN","M/S SPECTRUM COAL AND POWER LIMITED- SCPL","M/S S.V.POWER PVT.LTD.- SVPO"];

var aCoalFldCKP=["STEEL AUTHORITY OF INDIA- SAIL",
"TATA STEEL LIMITED- TISC"];

var aCoalFldDHN=["BHARAT COKING COAL LTD- BCCL",
"CENTRAL COAL FIELD LTD- CCL","DHORI- DHO","JHARIA- JRI","KARANPURA- KPA","MONET DANIEL COAL WASHERIES PVT LTD- MDCW","M/S ROSA POWER SUPPLY COMPANY LTD- RPSC","STEEL AUTHORITY OF INDIA LTD- SAIL","SINGRAULI- SGRL","TATA STEEL LTD- TISC"];

var aCoalFldHWH=["RAJMAHAL- RJL"
];

var aCoalFldKGP=["M/S TATA STEEL LIMITED- TISC"
];

var aCoalFldKUR=["M/S ARYAN ENERGY (P) LTD- AEPL",
"GLOBAL COAL AND MINING PVT LTD- GCML","M/S NEELACHAL ISPAT NIGAM LTD- NINL","M/S NLC TAMILNADU POWER LTD.- NTPL","SPECTRUM COAL AND POWER LTD- SCPL","SUKHINDA- SKND","TATA STEEL LIMITED- TISC","TALCHER COAL FIELDS- TLHR"];

var aCoalFldMLDT=["RAJMAHAL- RJL"
];

var aCoalFldNAG=["WESTERN COALFIELDS(CR)- WCFC"
];

var aCoalFldNGP=["INDO UNIQUE FLAME LIMITED- IUFL",
"KARNATAKA POWER BLOCK- KECM","KARNATAKA POWER BLOCK- KPB","MAHARASHTRA ELEKTROSMELT LTD- MELG","M. L. STONE WORK- MLSW","WESTERN COALFIELDS LTD- WCF","WESTERN COALFIELDS(CR)- WCFC"];

var aCoalFldR=["M/S MAHESWARI COAL BENEFICT. AND INFRA. PVT LTD- MCBI"
];

var aCoalFldRNC=["CENTRAL COAL FIELDS LIMITED- CCL"
];

var aCoalFldSBP=[];

var aCoalFldWAT=[];

