var aSpsrADRA=["M/S BHARAT COKING COAL LTD.- BCCL",
"M/S SAIL BOKARO STEEL PLANT- BSP","M/S CENTRAL COAL FIELD LTD.- CCL","M/S EASTERN COAL FIELD- ECF","M/S STEEL AUTHORITY OF INDIA LTD.- SAIL","M/S TATA STEEL LIMITED- TISC"];


var aSpsrASN=["M/S BHARAT COKING COAL LTD.- BCCL",
"M/S BENGAL EMTA COALS MINES LTD.- BCTP","M/S CENTRAL COAL FIELD LTD.- CCL","M/S CALCUTTA ELECTRIC SUPPLY CORP.- CESC","M/S DURGAPUR PROJECTS LTD.- DPLT","M/S EASTERN COAL FIELD- ECF","M/S INTEGRATED COAL MINES LTD- INCM","M/S IISCO STEEL PLANT- ISP","M/S STEEL AUTHORITY OF INDIA LTD.- SAIL","M/S TARA CAPTIVE MINES EMTA COAL MINES LTD- TCMB"];

var aSpsrBSP=["M/S ACB (INDIA) LIMITED- ACB",
"M/S BHARAT ALLUMINIUM COMPANY LTD.- BALC","M/S BHATIA ENERGY AND MINERALS PVT. LTD- BEMP","M/S CLEAN COAL ENTERPRISES PVT LTD- CCEP","M/S GLOBAL COAL AND MINING PVT LTD- GCML","HIND ENERGY AND COAL BENEFICATION(INDIA) LTD- HECB","M/S INDUS UDYOG AND INFRASTRUCTURE PVT. LTD- INDU","M/S JINDAL POWER LTD- JDPL","M/S JINDAL STEEL AND POWER LTD- JSPL","M/S MAHESWARI COAL BENEFICT. AND INFRA. PVT LTD- MCBI","M/S MAHANADI COALFIELD LTD.- MCFL","M/S MAHAVIR COAL WASHERIES PRIVATE LIMITED- MCWP","M/S MAHAVIR BENEFICATION PRIVATE LIMITED- MHBN","M/S PHIL COAL BENEFICATION PVT.LTD.- PCPB","PHIL MINERALS BENEFICATION AND ENERGY PVT LTD- PMBE","M/S RAJASTHAN RAJYA VIDYUT UTPADAN NIGAM LTD- RRVU","RAJASTHAN VIDYUT UTPADAN NIGAM LTD. (RVUNL)- RVUN","M/S SPECTRUM COAL AND POWER LIMITED- SCPL","M/S SOUTH EASTERN COALFIELD LTD.- SECL","M/S S.V.POWER PVT.LTD.- SVPO"];

var aSpsrCKP=["M/S STEEL AUTHORITY OF INDIA LTD.- SAIL",
"M/S TATA STEEL LIMITED- TISC"];


var aSpsrDHN=["M/S ADANI POWER MAHARASTRA LTD.- ADML",
"M/S ADANI POWER LTD.- ADPL","M/S ADHUNIK POWER AND NATURAL RESOURCES LTD U-1- APNR","M/S ADANI POWER RAJASTHAN LTD.,KAWAI- APRL","BHARAT COKING COAL LTD.- BCCL","M/S BAJAJ ENERGY PVT. LTD.- BJEP","CENTRAL COAL FIELD LTD.- CCL","THE INDIAN IRON AND STEEL COMPANY LTD- ISSC","M/S LALITPUR POWER GENERATION COMPANY LIMITED- LPGC","MONET DANIEL COAL WASHERY PVT. LTD.- MDCW","NORTHERN COALFIELDS LIMITED- NCL","M/S ROSA POWER SUPPLY COMPANY LTD- RPSC","M/S STEEL AUTHORITY OF INDIA LTD.- SAIL","TATA STEEL LIMITED- TISC"];

var aSpsrHWH=["M/S BENGAL EMTA COALS MINES LTD.- BCTP",
"M/S PANEM COAL MINES LIMITED- PCML","M/S TARA CAPTIVE MINES EMTA COAL MINES LTD- TCMB"];


var aSpsrKGP=["M/S TATA STEEL LIMITED- TISC"
];

var aSpsrKUR=["M/S ARYAN ENERGY (P) LTD.- AEPL",
"M/S GLOBAL COAL AND MINING PVT LTD- GCML","M/S JINDAL STAINLESS LTD.- JISL","M/S MAHANADI COALFIELD LTD.- MCFL","M/S NEELACHAL ISPAT NIGAM LTD- NINL","M/S NLC TAMILNADU POWER LTD.- NTPL","M/S SPECTRUM COAL AND POWER LIMITED- SCPL","M/S TATA STEEL LIMITED- TISC"];

var aSpsrMLDT=["M/S EASTERN COAL FIELD- ECF"
];

var aSpsrNAG=["M/S WESTERN COAL FIELD LTD.- WCF"
];

var aSpsrNGP=["M/S BALAJI TRADERS- BLJT",
"M/S INDO UNIQUE FLAME LIMITED- IUFL","M/S KARNATAKA EMTA COAL MINES LTD- KECM","M/S MAHARASHTRA ELEKTROSMELT LTD- MELG","M/S M. L. STONE WORK- MLSW","M/S WESTERN COAL FIELD LTD.- WCF"];

var aSpsrR=["M/S MAHESWARI COAL BENEFICT. AND INFRA. PVT LTD- MCBI"
];

var aSpsrRNC=["M/S CENTRAL COAL FIELD LTD.- CCL"
];

var aSpsrSBP=[];

var aSpsrWAT=[];
