var aZoneDvsnSW=["BANGALORE- SBC",
"HUBLI- UBL","MYSORE- MYS"];

var aZoneDvsnSE=["ADRA- ADRA",
"CHAKRADHAR PUR- CKP","KHARAGPUR- KGP","RANCHI- RNC"];

var aZoneDvsnECO=["KHURDA ROAD- KUR",
"SAMBALPUR- SBP","WALTAIR- WAT"];